%YAML 1.2
---
language: python
python:
    - 2.7
    - 3.4
install:
    - pip install -r requires/testing.txt
    - pip install coverage
script: nosetests -c setup.cfg --with-coverage --cover-package=sprockets
